### ISSUE TITLE
'master' branch in this repo doesn't match 'master' in KEDA repo

### ISSUE THREAD

**Issue by eashi** [kedacore/sample-go-rabbitmq#2]
The `master` branch in this repo is synchronized with the KEDA container tagged by `latest`, which is NOT the `master` in KEDA repo. 

This adds confusion if there is a breaking change in `master` KEDA, just like the fix [#347](https://github.com/kedacore/keda/pull/347) for resolving the host from environment.

Should `master` of this repo synchronise with `master` in KEDA? Or maybe put a statement at the beginning of README.md that you should check branch `x` if you are using a KEDA that was built from `master`.

I feel the release story can be a little better?

**Comment by jeffhollan** [comment]
Yep makes sense - some awkwardness for this sample specifically as was impacted by a breaking change before we moved KEDA to 1.0 and started using explicit version tags.  That has been cleared up and we have a better release process now. Let me know if any other pending items here.

https://github.com/kedacore/keda/wiki/Release-process
